version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    depends_on:
      - rubyai-opensearch-node
    networks:
      - rubyai-search-network

  rubyai-opensearch-node:
    image: opensearchproject/opensearch:2.18.0
    container_name: rubyai-opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=rubyai-opensearch-node
      - discovery.type=single-node
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - rubyai-opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - rubyai-search-network

  rubyai-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: rubyai-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://rubyai-opensearch-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - rubyai-opensearch-node   
    networks:
      - rubyai-search-network

volumes:
  rubyai-opensearch-data:

networks:
  rubyai-search-network:
    name: rubyai-search-network
