services:
  jupyter:
    image: rubydata/datascience-notebook
    restart: unless-stopped
    environment:
      - TZ=America/NewYork
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
